const express = require('express');
const router = express.Router();
const path = require('path');
const request = require('request');
const authorizedControllers = require('../controllers/authorized');
router.get('/saved',authorizedControllers.saved);
router.get('/',authorizedControllers.getHome);
router.post('/',authorizedControllers.postHome);
router.get('/logout',authorizedControllers.logout);
module.exports = router;